version: '2.2'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ${PWD}/django:/django
    restart: unless-stopped
    # networks:
    #   - transcendence
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres 
    restart: always
    environment:
       POSTGRES_USER: ${POSTGRES_DB_USER}
       POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB_NAME}
       POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    # networks:
    #   - transcendence
    volumes: 
    - ./pg_hba.conf:/var/lib/foo/pg_hba.conf
    command: ["postgres", "-c", "hba_file=/var/lib/foo/pg_hba.conf"]

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/tools:/etc/nginx/ssl/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
    restart: always

# networks:
#   transcendence:
#     driver: bridge

# volumes:
#   postgres_db:
#     driver: local
