# Generated by Django 4.2.11 on 2024-04-26 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_user_options_alter_user_managers_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 15, 52, 9, 166476)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 15, 52, 9, 166476)),
        ),
    ]
