# Generated by Django 4.2.11 on 2024-04-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_managers_alter_match_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='dmchannel',
            name='channel_ptr',
        ),
        migrations.RemoveField(
            model_name='dmchannel',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='dmchannel',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='match',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='win',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='DMChannel',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
