# Generated by Django 4.2.11 on 2024-05-01 19:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_chat_channels_remove_dmchannel_channel_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.IntegerField(default=0)),
                ('p2_score', models.IntegerField(default=0)),
                ('start', models.DateTimeField(default=datetime.datetime(2024, 5, 1, 23, 34, 25, 627457))),
                ('end', models.DateTimeField(null=True)),
                ('lose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_player', to=settings.AUTH_USER_MODEL)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL)),
                ('win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
