# Generated by Django 4.2.11 on 2024-05-04 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 19, 38, 23, 803615)),
        ),
    ]
