# Generated by Django 4.2.11 on 2024-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_alter_match_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='win',
            new_name='winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='lose',
        ),
        migrations.AlterField(
            model_name='match',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
