# Generated by Django 4.2.11 on 2024-05-15 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_rename_win_match_winner_remove_match_lose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
