# Generated by Django 4.2.11 on 2024-05-18 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_alter_channel_owner_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='messages',
            field=models.ManyToManyField(default=[], to='backend.message'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(default=[], to=settings.AUTH_USER_MODEL),
        ),
    ]
