# Generated by Django 4.2.11 on 2024-05-21 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_alter_channel_messages_alter_channel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='blocked',
            field=models.ManyToManyField(default=[], related_name='blocked_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(default=[], related_name='chat_memebrs', to=settings.AUTH_USER_MODEL),
        ),
    ]
