# Generated by Django 4.2.11 on 2024-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_channel_blocked_alter_channel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
