# Generated by Django 4.2.11 on 2024-05-23 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_remove_message_is_tournament_match_is_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='awaiting_players',
            field=models.ManyToManyField(default=[], related_name='awaiting_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
