# Generated by Django 4.2.11 on 2024-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_match_awaiting_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_42_user',
            field=models.BooleanField(default=False),
        ),
    ]
