# Generated by Django 4.2.11 on 2024-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0090_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
