# Generated by Django 4.2.11 on 2024-05-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_alter_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
